=begin
#qTest Manager API Version 8.6 - 9.1

#qTest Manager API Version 8.6 - 9.1

OpenAPI spec version: 8.6 - 9.1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ReleaseApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReleaseApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ReleaseApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReleaseApi' do
    it 'should create an instact of ReleaseApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ReleaseApi)
    end
  end

  # unit tests for create
  # Creates a Release
  # To create a Release  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 4+
  # @param project_id ID of the project
  # @param body The Release&#39;s properties
  # @param [Hash] opts the optional parameters
  # @return [ReleaseWithCustomFieldResource]
  describe 'create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete
  # Delete a release
  # To delete a Release
  # @param project_id ID of the project
  # @param release_id ID of the Release which needs to be deleted  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 6+
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # Gets a Release
  # To retrieve a Release  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 4+
  # @param project_id ID of the project
  # @param release_id ID of the Release
  # @param [Hash] opts the optional parameters
  # @return [ReleaseWithCustomFieldResource]
  describe 'get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all
  # Gets multiple Releases
  # To retrieve Releases in a project  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 4+
  # @param project_id ID of the project
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :include_closed &lt;em&gt;includeClosed&#x3D;false&lt;/em&gt; - default value. &lt;em&gt;Closed&lt;/em&gt; Releases are excluded from the response  &lt;em&gt;includeClosed&#x3D;false&lt;/em&gt; - Closed Release are included in the response
  # @return [Array<ReleaseWithCustomFieldResource>]
  describe 'get_all test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update
  # Updates a Release
  # To update a Release  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 6+
  # @param project_id ID of the project
  # @param release_id ID of the Release which needs to be updated
  # @param body The Release&#39;s updated properties
  # @param [Hash] opts the optional parameters
  # @return [ReleaseWithCustomFieldResource]
  describe 'update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
