=begin
#qTest Manager API Version 8.6 - 9.1

#qTest Manager API Version 8.6 - 9.1

OpenAPI spec version: 8.6 - 9.1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TestsuiteApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TestsuiteApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TestsuiteApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TestsuiteApi' do
    it 'should create an instact of TestsuiteApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TestsuiteApi)
    end
  end

  # unit tests for create_test_suite
  # Creates a Test Suite
  # To create a new Test Suite  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 6+
  # @param project_id ID of the project
  # @param body The Test Suite&#39;s properties
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :parent_id ID of the Release or Test Cycle under which the newly created Test Suites are located. Input 0 (zero) to create Test Suites directly under root
  # @option opts [String] :parent_type Arifact type of the container. Valid values include &lt;em&gt;release&lt;/em&gt;, &lt;em&gt;test-cycle&lt;/em&gt; and &lt;em&gt;root&lt;/em&gt;
  # @return [TestSuiteWithCustomFieldResource]
  describe 'create_test_suite test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete
  # Deletes a Test Suite
  # To delete a Test Suite  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 6+
  # @param project_id ID of the project
  # @param test_suite_id ID of the Test Suite.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # Gets multiple Test Suite
  # To retrieve Test Suites which located under a parent Release, Test Cycle or root  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 6+
  # @param project_id ID of the project
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :parent_id ID of the Release or Test Cycle under which the Test Suites are located. Input 0 (zero) to get Test Suites directly under root
  # @option opts [String] :parent_type Arifact type of the container. Valid values include &lt;em&gt;release&lt;/em&gt;, &lt;em&gt;test-cycle&lt;/em&gt; and &lt;em&gt;root&lt;/em&gt;
  # @return [Array<TestSuiteWithCustomFieldResource>]
  describe 'get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_test_suite
  # Gets a Test Suite
  # To retrieve a Test Suite  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 6+
  # @param project_id ID of the project
  # @param test_suite_id ID of the Test Suite
  # @param [Hash] opts the optional parameters
  # @return [TestSuiteWithCustomFieldResource]
  describe 'get_test_suite test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_test_suite
  # Updates a Test Suite
  # To update an existing Test Suite or to move it to other container  &lt;strong&gt;Important:&lt;/strong&gt; If you use the request parameters &lt;em&gt;parentId&lt;/em&gt; and &lt;em&gt;parentType&lt;/em&gt;, the request body will be ignore.   That means the Test Suite is being moved but it will not be updated with the properties specify in the request body
  # @param project_id ID of the project
  # @param test_suite_id ID of the Test Suite
  # @param body The Test Suite&#39;s updated properties
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :parent_id ID of the Release or Test Cycle which the Test Suite will be moved to. Input 0 (zero) to move the Test Suite to under root
  # @option opts [String] :parent_type Artifact type of the parent container. Valid values include &lt;em&gt;release&lt;/em&gt;, &lt;em&gt;test-cycle&lt;/em&gt; and &lt;em&gt;root&lt;/em&gt;
  # @option opts [BOOLEAN] :no_email 
  # @return [TestSuiteWithCustomFieldResource]
  describe 'update_test_suite test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
