=begin
#qTest Manager API Version 8.6 - 9.1

#qTest Manager API Version 8.6 - 9.1

OpenAPI spec version: 8.6 - 9.1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TestcycleApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TestcycleApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TestcycleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TestcycleApi' do
    it 'should create an instact of TestcycleApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TestcycleApi)
    end
  end

  # unit tests for create_cycle
  # Create a Test Cycle
  # To create a Test Cycle  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 6+
  # @param project_id ID of the project
  # @param body Given resource to create a test cycle.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :parent_id ID of the Release or Test Cycle under which the newly created Test Cycle will be located.   Use 0 (zero) to create the Test Cycle under the root
  # @option opts [String] :parent_type The artifact type of the parent folder. Valid values include &lt;em&gt;release&lt;/em&gt;, &lt;em&gt;test-cycle&lt;/em&gt; or &lt;em&gt;root&lt;/em&gt;
  # @return [TestCycleResource]
  describe 'create_cycle test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_cycle
  # Deletes a Test Cycle
  # To delete a Test Cycle  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 6+
  # @param project_id ID of the project
  # @param test_cycle_id ID of the Test Cycle which needs to be deleted.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :force The Test Cycle can only be deleted if it contains no children. Specify &lt;em&gt;force&#x3D;true&lt;/em&gt; to delete the Test Cycle and its children
  # @return [Message]
  describe 'delete_cycle test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_test_cycle
  # Gets a Test Cycle
  # To retrieve a Test Cycle  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 6+
  # @param project_id ID of the project
  # @param test_cycle_id ID of the Test Cycle which you want to retrieve.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand Specify &lt;em&gt;expand&#x3D;descendants&lt;/em&gt; to include its sub and grand-sub Test Cycles and Test Suites in the response
  # @return [TestCycleResource]
  describe 'get_test_cycle test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_test_cycles
  # Gets multiple Test Cycles
  # To retrieve Test Cycles which are located directly under root or a Release/Test Cycle
  # @param project_id ID of the project
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :parent_id ID of the Release or Test Cycle which directly contains the Test Cycles you are retrieving. Input 0 (zero) to get Test Cycles directly under root
  # @option opts [String] :parent_type The artifact type of the parent folder. Valid values include &lt;em&gt;release&lt;/em&gt;, &lt;em&gt;test-cycle&lt;/em&gt; or &lt;em&gt;root&lt;/em&gt;
  # @option opts [String] :expand Specify &lt;em&gt;expand&#x3D;descendants&lt;/em&gt; to retrieve the Test Cycles&#39; sub and grand-sub Cycles/Suites
  # @return [Array<TestCycleResource>]
  describe 'get_test_cycles test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_cycle
  # Updates a Test Cycle
  # To update a Test Cycle or move it to another container  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 6+
  # @param project_id ID of the project
  # @param test_cycle_id ID of the Test Cycle which needs to be updated.
  # @param body The Test Cycle&#39;s updated properties
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :parent_id ID of a Release or parent Test Cycle which the updated Test Cycle will be moved to. Input 0 (zero) to move the Test Cycle to under root
  # @option opts [String] :parent_type The artifact type of the parent folder to which the Test Cycle will be moved to. Valid values include &lt;em&gt;release&lt;/em&gt;, &lt;em&gt;test-cycle&lt;/em&gt; or &lt;em&gt;root&lt;/em&gt;
  # @return [TestCycleResource]
  describe 'update_cycle test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
