=begin
#qTest Manager API Version 8.6 - 9.1

#qTest Manager API Version 8.6 - 9.1

OpenAPI spec version: 8.6 - 9.1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::UserprofileApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserprofileApi' do
  before do
    # run before each test
    @instance = SwaggerClient::UserprofileApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserprofileApi' do
    it 'should create an instact of UserprofileApi' do
      expect(@instance).to be_instance_of(SwaggerClient::UserprofileApi)
    end
  end

  # unit tests for batch_assign_user_profile_in_client
  # Assigns multiple Users to a Profile
  # To batch assign users to a profile (Admin profile, User profile) (as in qTest Manager &lt;em&gt;admin panel&lt;/em&gt;). It requires that your qTest Manager profile is a site admin with &lt;em&gt;Manage Client Users&lt;/em&gt; permissions  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 8.4.2+
  # @param body An array of user IDs and admin and/or normal user profile
  # @param [Hash] opts the optional parameters
  # @return [Array<UserResourceExtension>]
  describe 'batch_assign_user_profile_in_client test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for batch_assign_user_profile_in_project
  # Assigns multiple Users to a Profile in a Project
  # To change profile of assigned users (as a project&#39;s User Management page). It requires that your qTest Manager profile within the project is Project Admin  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 8.4.2+
  # @param project_id ID of the project
  # @param body An array of user IDs and a user profile
  # @param [Hash] opts the optional parameters
  # @return [Array<UserResourceExtension>]
  describe 'batch_assign_user_profile_in_project test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_current
  # Gets current User&#39;s Admin Profile
  # To retrieve your Admin Profile  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 4+
  # @param [Hash] opts the optional parameters
  # @return [AdminProfile]
  describe 'get_current test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_profiles_of_current_user
  # Gets current User&#39;s Profiles in different Projects
  # To retrieve your User Profiles in different Projects
  # @param [Hash] opts the optional parameters
  # @return [Array<UserProfile>]
  describe 'get_profiles_of_current_user test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_profiles
  # Gets available Profiles
  # To retrieve all available profiles in your qTest Manager instance. It requires that your qTest Manager profile is a site admin with &lt;em&gt;View User Profiles&lt;/em&gt; permissions  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 8.4.2+
  # @param [Hash] opts the optional parameters
  # @option opts [String] :type &lt;em&gt;type&#x3D;admin&lt;/em&gt; - to retrieve only admin profiles  &lt;em&gt;type&#x3D;use&lt;/em&gt; - to retrieve only normal user profiles  Omit this parameter to include both
  # @return [UserProfileResponse]
  describe 'get_user_profiles test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
