=begin
#qTest Manager API Version 8.6 - 9.1

#qTest Manager API Version 8.6 - 9.1

OpenAPI spec version: 8.6 - 9.1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/admin_profile'
require 'swagger_client/models/allowed_value_resource'
require 'swagger_client/models/app_detail'
require 'swagger_client/models/artifact_history_resource'
require 'swagger_client/models/artifact_search_params'
require 'swagger_client/models/assigned_project'
require 'swagger_client/models/assigned_users_project'
require 'swagger_client/models/attachment_author'
require 'swagger_client/models/attachment_resource'
require 'swagger_client/models/automation_request'
require 'swagger_client/models/automation_schedule_creation_api'
require 'swagger_client/models/automation_step_log'
require 'swagger_client/models/automation_test_log'
require 'swagger_client/models/automation_test_log_resource'
require 'swagger_client/models/automation_test_step_log'
require 'swagger_client/models/build_permission'
require 'swagger_client/models/build_resource'
require 'swagger_client/models/comment_query_params'
require 'swagger_client/models/comment_resource'
require 'swagger_client/models/defect_field_mapping'
require 'swagger_client/models/defect_mapping'
require 'swagger_client/models/defect_permission'
require 'swagger_client/models/defect_resource'
require 'swagger_client/models/defect_tracking_system'
require 'swagger_client/models/field_resource'
require 'swagger_client/models/history_change'
require 'swagger_client/models/history_query_params'
require 'swagger_client/models/history_resource'
require 'swagger_client/models/link'
require 'swagger_client/models/linked_artifact'
require 'swagger_client/models/linked_artifact_container'
require 'swagger_client/models/linked_defect_resource'
require 'swagger_client/models/linked_object'
require 'swagger_client/models/logged_user'
require 'swagger_client/models/manual_test_log_resource'
require 'swagger_client/models/message'
require 'swagger_client/models/module_permission'
require 'swagger_client/models/module_resource'
require 'swagger_client/models/o_auth_response'
require 'swagger_client/models/output_stream'
require 'swagger_client/models/paged_resource'
require 'swagger_client/models/paged_resource_attachment_resource'
require 'swagger_client/models/paged_resource_comment_resource'
require 'swagger_client/models/profile'
require 'swagger_client/models/project_admin_permission'
require 'swagger_client/models/project_resource'
require 'swagger_client/models/project_setting_permission'
require 'swagger_client/models/project_users_profile'
require 'swagger_client/models/property_resource'
require 'swagger_client/models/query_comment_resource'
require 'swagger_client/models/queue_processing_response'
require 'swagger_client/models/release_permission'
require 'swagger_client/models/release_with_custom_field_resource'
require 'swagger_client/models/report_permission'
require 'swagger_client/models/requirement_permission'
require 'swagger_client/models/requirement_resource'
require 'swagger_client/models/resource_support'
require 'swagger_client/models/schedule_permission'
require 'swagger_client/models/search_user_resource'
require 'swagger_client/models/search_user_resource_extension_response'
require 'swagger_client/models/search_user_response'
require 'swagger_client/models/session_manager_permission'
require 'swagger_client/models/site_users_profile'
require 'swagger_client/models/status_resource'
require 'swagger_client/models/test_case_permission'
require 'swagger_client/models/test_case_with_custom_field_resource'
require 'swagger_client/models/test_cycle_permission'
require 'swagger_client/models/test_cycle_resource'
require 'swagger_client/models/test_log_list_resource'
require 'swagger_client/models/test_log_resource'
require 'swagger_client/models/test_run_list_resource'
require 'swagger_client/models/test_run_permission'
require 'swagger_client/models/test_run_with_custom_field_resource'
require 'swagger_client/models/test_step_log_resource'
require 'swagger_client/models/test_step_resource'
require 'swagger_client/models/test_suite_permission'
require 'swagger_client/models/test_suite_with_custom_field_resource'
require 'swagger_client/models/traceability_requirement'
require 'swagger_client/models/user_profile'
require 'swagger_client/models/user_profile_response'
require 'swagger_client/models/user_resource'
require 'swagger_client/models/user_resource_extension'

# APIs
require 'swagger_client/api/attachment_api'
require 'swagger_client/api/automationjob_api'
require 'swagger_client/api/build_api'
require 'swagger_client/api/common_api'
require 'swagger_client/api/defect_api'
require 'swagger_client/api/field_api'
require 'swagger_client/api/login_api'
require 'swagger_client/api/module_api'
require 'swagger_client/api/objectlink_api'
require 'swagger_client/api/project_api'
require 'swagger_client/api/release_api'
require 'swagger_client/api/requirement_api'
require 'swagger_client/api/search_api'
require 'swagger_client/api/testcase_api'
require 'swagger_client/api/testcycle_api'
require 'swagger_client/api/testlog_api'
require 'swagger_client/api/testrun_api'
require 'swagger_client/api/testsuite_api'
require 'swagger_client/api/user_api'
require 'swagger_client/api/userprofile_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
